/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package layer;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.awt.Desktop;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URISyntaxException;
import java.net.URL;
//import con;
//import con;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.icepdf.ri.common.ComponentKeyBinding;
import org.icepdf.ri.common.SwingController;
import org.icepdf.ri.common.SwingViewBuilder;

/**
 *
 * @author Abhishek
 */
public class panel3 extends javax.swing.JPanel {

    /**
     * Creates new form panel3
     */
     Connection con;
    PreparedStatement stmt;
    ResultSet rs;
    public panel3() {
         try {
             initComponents();
             BufferedImage bi=ImageIO.read(new File("C:\\Users\\Abhishek\\Downloads\\note-taking-feature.jpg"));
             Image im=bi.getScaledInstance(1700,1250,Image.SCALE_SMOOTH);
             ImageIcon mi=new ImageIcon(im);
             jLabel1.setIcon(mi);
//             BufferedImage bii=ImageIO.read(new File("C:\\Users\\Abhishek\\Downloads\\channels4_profile.jpg"));
//             Image imm=bii.getScaledInstance(200,200,Image.SCALE_SMOOTH);
//             ImageIcon mii=new ImageIcon(imm);
//             jLabel3.setIcon(mii);
//        int i;
//        for(i=1;i<=8;i++)
//        {
//            jComboBox1.addItem(i);
//        }
//       
//                 try
//        {
//       
//         Class.forName("com.mysql.jdbc.Driver");
//     con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/college","root","root");
//        
//        }
//        catch(ClassNotFoundException | SQLException ae)
//        {
//            System.out.println(ae);
//        }
//    }
//      void openpdf(String file)
//{
//    try
//    {
//       SwingController control=new SwingController();
//       SwingViewBuilder factory=new SwingViewBuilder(control);
//       JPanel veiwerCompntpnl=factory.buildViewerPanel();
//       ComponentKeyBinding.install(control, veiwerCompntpnl);
//       control.getDocumentViewController().setAnnotationCallback(
//               new org.icepdf.ri.common.MyAnnotationCallback(control.getDocumentViewController()));
//       control.openDocument(file);
//       
//       jScrollPane1.setViewportView(veiwerCompntpnl);
//       
//    }
//    catch(Exception ae)
//    {
//        System.out.print(ae);
//    }
         } catch (IOException ex) {
             Logger.getLogger(panel3.class.getName()).log(Level.SEVERE, null, ex);
         }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 102, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Abhishek\\Downloads\\images.jpeg")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 480, 280, 190));

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Abhishek\\Downloads\\zz.jpeg")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 480, 210, 210));

        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Abhishek\\Downloads\\Pyq.jpeg")); // NOI18N
        jButton3.setText("jButton1");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 470, 210, 210));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1650, 1020));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
//            File file =new File("https://drive.google.com/drive/folders/117rCdd012batCdoDLz1Ihu08xe7AZbf1?usp=sharing");
            
                if(Desktop.isDesktopSupported())
                {
                    try {
                        Desktop.getDesktop().browse(new URL("https://notesolves.hideandseekapps.com/practicals-cse").toURI());
                    } catch (IOException | URISyntaxException ex) {
                        Logger.getLogger(panel3.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                else
                {
                     JOptionPane.showMessageDialog(this,"Wrong Registration Id","Enter Correct Registration Id",JOptionPane.INFORMATION_MESSAGE);
                }
            
        }
        catch(HeadlessException e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         try{
//            File file =new File("https://drive.google.com/drive/folders/117rCdd012batCdoDLz1Ihu08xe7AZbf1?usp=sharing");
            
                if(Desktop.isDesktopSupported())
                {
                    try {
                        Desktop.getDesktop().browse(new URL("https://notesolves.hideandseekapps.com/pyq-cse").toURI());
                    } catch (IOException | URISyntaxException ex) {
                        Logger.getLogger(panel3.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                else
                {
                     JOptionPane.showMessageDialog(this,"Wrong Registration Id","Enter Correct Registration Id",JOptionPane.INFORMATION_MESSAGE);
                }
            
        }
        catch(HeadlessException e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         try{
//            File file =new File("https://drive.google.com/drive/folders/117rCdd012batCdoDLz1Ihu08xe7AZbf1?usp=sharing");
            
                if(Desktop.isDesktopSupported())
                {
                    try {
                        Desktop.getDesktop().browse(new URL("https://notesolves.hideandseekapps.com/notes-cse").toURI());
                    } catch (IOException | URISyntaxException ex) {
                        Logger.getLogger(panel3.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                else
                {
                     JOptionPane.showMessageDialog(this,"Wrong Registration Id","Enter Correct Registration Id",JOptionPane.INFORMATION_MESSAGE);
                }
            
        }
        catch(HeadlessException e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
